#! /usr/bin/ruby
# frozen_string_literal: true

if Dir.glob("#{ENV['HOME']}/esp").any?
  puts 'Oops - looks like you already have ESP-IDF installed at ~/esp.'
  puts 'Remove this ESP-IDF installation before starting? (y/n)'
  exit unless gets.rstrip == 'y'

  system('rm -rf ~/esp')
end

if Dir.glob('/usr/local/bin/pip').none?
  puts 'Installing pip'
  system('sudo easy_install pip')
end

puts 'Creating the ESP folder'
system('mkdir -p ~/esp')

puts 'Installing ESP-IDF v3.3'
system('git clone -b v3.3 --recursive --recurse-submodules https://github.com/espressif/esp-idf.git ~/esp/esp-idf')

puts 'Installing ESP-IDF requirements'
system('python -m pip install --user -r ~/esp/esp-idf/requirements.txt')

puts 'Install Xtensa-ESP32-elf'
system('wget -O ~/esp/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz')
system('tar -xzf ~/esp/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz -C ~/esp')
system('rm ~/esp/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz')

puts 'Installing Soulmate...'
system('git clone --recursive --recurse-submodules git@github.com:Soulmate-Lights/soulmate-core.git ~/esp/soulmate')

puts 'Done!'
puts 'To compile your Soulmate code, use ./run'
