COMPONENT_SRCDIRS := .
CPPFLAGS += -Wno-error=switch -Wno-error=maybe-uninitialized
EXTRA_COMPONENT_DIRS += $(HOME)/soulmate/esp-idf/components
EXTRA_COMPONENT_DIRS += $(HOME)/soulmate
EXTRA_COMPONENT_DIRS += $(HOME)/soulmate/components
PROJECT_NAME := soulmate
MAKEFLAGS +=
include $(HOME)/soulmate/esp-idf/make/project.mk
