name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install esp-idf
      run: |
        mkdir -p ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git ~/esp/esp-idf
        ~/esp/esp-idf/install.sh
    - name: make
      run: |
        . $HOME/esp/esp-idf/export.sh
        make -C builder
