name: C/C++ CI

on:
  push:
    branches: [master, elliott/builds]
  pull_request:
    branches: [master, elliott/builds]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: build
        run: docker build --tag soulmate-dev .
      - name: make
        run: docker run --rm soulmate-dev make -j3 -C builder
