name: C/C++ CI

on:
  push:
    branches: [master, elliott/builds]
  pull_request:
    branches: [master, elliott/builds]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDF_PATH: /home/runner/esp/esp-idf
      SOULMATE_PATH: /home/runner/work/soulmate-core/soulmate-core

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: install toolchain
        run: sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-serial
      - name: install esp-idf
        run: |
          mkdir -p /home/runner/esp
          git clone -b release/v3.3 --recursive https://github.com/espressif/esp-idf.git /home/runner/esp/esp-idf
          /home/runner/esp/esp-idf/install.sh
      - name: pip
        run: python -m pip install --user -r /home/runner/esp/esp-idf/requirements.txt
      - name: copy main.cpp
        run: cp builder/_main.cpp builder/main/main.cpp
      - name: make
        run: |
          . /home/runner/esp/esp-idf/export.sh
          make -C builder
